# -*- coding: utf-8 -*-
"""BankCaseStudy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tf81ARPKG68cGFsXEb_30Cj412ZIhIu8

create a bank class 
has amount,accountno,name createaccount(constructor)-user only gives name and amount 
account number auto generated withdraw(amount):should not be -ve amount and min balance is 2000 else reject transection deposite(amount):amount can not be -ve checkbalance():shows balance and account holder name

'''
menu driven code to 
1 create account
2 withdraw
3 deposite
4 check balance

1---->create by taking values and auto generate account number
2/3/4--->ask account number ,search account and then operate
"""

class Bank:
  count=2303000
  def __init__ (self,name,amount):
    Bank.count+=1
    self.id=Bank.count
    self.name=name
    self.amount=amount
    self.balance=amount
    print('Your Customer ID:',self.id)
  def withdraw(self,wamount):
    self.wamount=wamount
    if wamount<=0:
      print('Invalid Amount')
    elif self.balance<2000:
      print('Balance cannot be less than Rs 2000')
    else:
      self.balance-=wamount
      print('Transaction Processed. Your Balance:',self.balance)
  def deposit(self,damount):
    self.damount=damount
    if damount>0:
      print('Rs',self.damount,'are deposited.')
      self.balance+=damount
      print('Balance:',self.balance)
    else:
      print('Wrong Amount')
  def getcid(self):
    return self.id
  def __str__ (self):
    return str(self.balance)

custlist=[]
while True:
    print("1.Create Acc\n2.Withdraw\n3.Deposit\n4.Check Balance\n0.Exit")
    ch=int(input(":"))
    if ch==1:
        n=input("Enter name:")
        s=float(input("amount(Minimum Rs 2000 to create account):"))
        e=Bank(n,s)
        custlist.append(e)
    elif ch==2:
      tempcid=int(input("Enter Your Customer id:"))
      flag=False
      for i in custlist:
          if i.getcid()==tempcid:
              print('Processing Transacation')
              flag=True
              wamount=float(input('Enter amount:'))
              e.withdraw(wamount)
              break
      if flag==False:
            print("Not Found")
    elif ch==3:
        tempcid=int(input("Enter Your Customer id:"))
        flag=False
        for i in custlist:
            if i.getcid()==tempcid:
                print('Processing Transacation')
                flag=True
                damount=float(input('Enter amount:'))
                e.deposit(damount)
                break
        if flag==False:
            print("Not Found")
    elif ch==4:
      tempcid=int(input("Enter Your Customer id:"))
      flag=False
      for i in custlist:
          if i.getcid()==tempcid:
              flag=True
              print(e)
              break
      if flag==False:
          print("Not Found")
    elif ch==0:
        print('Thanks for using our service, Bye')
        break
    else:
      print('Wrong Choice')